openapi: 3.0.3
info:
  title: Développement d'API REST avec Ktor
  version: 1.0.0
  description: My API description
  contact:
    name: My API Team
    email: bidon@gmail.com
paths:
  /teams:
    get:
      description: Get all teams
      summary: Get all teams
      operationId: getTeams
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team' # Mise à jour du chemin de référence
components:
  schemas:
    Team:   # Ajout de la définition du schéma Team
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
